apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  NAME: dG9kb2Ri # tododb in base64
  USER: dG9kb2FwcF91c2Vy # totoapp_user in base64
  PASSWORD: bXktc2VjcmV0LXVzZXJfcHc= # my-secret-user_pw in base64
  HOST: dG9kb2FwcC1teXNxbC0wLnRvZGFwcC1teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA== # todoapp-mysql-0.todapp-mysql.mysql.svc.cluster.local in base64