apiVersion: v1
kind: Secret
metadata:
  name: todoapp-mysql-secret
  namespace: mysql
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  MYSQL_ROOT_PASSWORD: bXktc2VjcmV0LXB3
  MYSQL_USER: dG9kb2FwcF91c2Vy
  MYSQL_PASSWORD: bXktc2VjcmV0LXVzZXJfcHc=